package main

import (
	"bytes"
	"fmt"
	"regexp"
	"sort"
	"strings"
)

var handlerResponseTypes = map[string]string{
	// Auth handlers
	"SignUp":                   "AuthResponse",
	"SignIn":                   "AuthResponse",
	"SignOut":                  "MessageResponse",
	"VerifyEmail":              "MessageResponse",
	"GetCurrentSession":        "CurrentSessionResponse | null",
	"UpdateUser":               "UpdateUserResponse",
	"ChangePassword":           "MessageResponse",
	"RequestEmailVerification": "RequestVerificationResponse",
	"ListSessions":             "SessionListItem[]",
	"RevokeSession":            "MessageResponse",
	"GetUserPermissions":       "UserPermissionsResponse",

	// Health
	"GetHealth": "HealthResponse",

	// Admin - Roles
	"GetPermissions": "string[]",
	"ListRoles":      "Role[]",
	"CreateRole":     "Role",
	"GetRole":        "Role",
	"UpdateRole":     "Role",
	"DeleteRole":     "MessageResponse",
	"AssignRole":     "MessageResponse",
	"RemoveRole":     "MessageResponse",

	// Admin - Users
	"ListUsers": "PaginatedResponse<User>",
	"BanUser":   "MessageResponse",
	"UnbanUser": "MessageResponse",

	// Admin - Dashboard
	"GetDashboardStats": "DashboardStats",

	// Admin - Settings
	"GetSiteSettings":          "SiteSettings",
	"UpdateSiteSettings":       "SiteSettings",
	"GetSystemInfo":            "SystemInfo",
	"PerformMaintenanceAction": "MaintenanceActionResponse",

	// Admin - Tags
	"ListTags":  "Tag[]",
	"CreateTag": "Tag",
	"UpdateTag": "Tag",
	"DeleteTag": "MessageResponse",

	// Admin - Series
	"ListSeries":   "PaginatedResponse<Series>",
	"CreateSeries": "Series",
	"GetSeries":    "Series",
	"UpdateSeries": "Series",
	"DeleteSeries": "MessageResponse",

	// Admin - Chapters
	"ListChapters":  "Chapter[]",
	"CreateChapter": "Chapter",
	"UpdateChapter": "Chapter",
	"DeleteChapter": "MessageResponse",
	"AddPages":      "Page[]",
	"ReorderPages":  "MessageResponse",
	"UpdatePage":    "Page",
	"DeletePage":    "MessageResponse",

	// Admin - GetChapter returns ChapterWithPages, Public GetChapter returns ChapterReader
	// We handle this by path prefix in getResponseType function

	// Admin - Upload
	"UploadFile":          "AsyncUploadResponse",
	"UploadMultipleFiles": "AsyncBulkUploadResponse",
	"GetUploadStatus":     "UploadStatusResponse",
	"CleanOrphanedFiles":  "MessageResponse",

	// Public - Manga
	"GetSeriesBySlug": "SeriesWithChapters",

	// Public - Chapters
	"IncrementSeriesView":  "MessageResponse",
	"IncrementChapterView": "MessageResponse",

	// Bookmarks
	"ListBookmarks":     "Bookmark[]",
	"GetBookmarkStatus": "BookmarkStatusResponse",
	"ToggleBookmark":    "ToggleBookmarkResponse",

	// Admin - Task Management
	"ListQueues":             "QueueListResponse",
	"GetQueueInfo":           "QueueInfo",
	"ListTasks":              "TaskListResponse",
	"GetTask":                "TaskInfo",
	"RunTask":                "MessageResponse",
	"ArchiveTask":            "MessageResponse",
	"DeleteTask":             "MessageResponse",
	"PauseQueue":             "MessageResponse",
	"UnpauseQueue":           "MessageResponse",
	"GetHistory":             "{ history: DailyStats[] }",
	"ListServers":            "{ servers: ServerInfo[] }",
	"GetStats":               "TaskStatsResponse",
	"RunAllScheduledTasks":   "{ message: string; count: number }",
	"RunAllRetryTasks":       "{ message: string; count: number }",
	"DeleteAllArchivedTasks": "{ message: string; count: number }",
}

func Generate(result *ParseResult, config Config) string {
	var buf bytes.Buffer

	typesToImport := collectTypes(result)

	// Header
	buf.WriteString("// Code generated by @docix/codegen. DO NOT EDIT.\n")
	buf.WriteString("// Run `pnpm generate` to regenerate this file.\n\n")

	// Imports from @docix/types (tygo-generated)
	if len(typesToImport) > 0 {
		sortedTypes := make([]string, 0, len(typesToImport))
		for t := range typesToImport {
			sortedTypes = append(sortedTypes, t)
		}
		sort.Strings(sortedTypes)

		buf.WriteString("import type {\n")
		for _, t := range sortedTypes {
			fmt.Fprintf(&buf, "\t%s,\n", t)
		}
		fmt.Fprintf(&buf, "} from \"%s\";\n", config.TypesPackage)
	}

	buf.WriteString("import { mutationOptions, queryOptions } from \"@tanstack/react-query\";\n")
	buf.WriteString("import axios, { type AxiosRequestConfig } from \"axios\";\n\n")

	buf.WriteString("export const api = axios.create({\n")
	buf.WriteString("\tbaseURL: process.env.NEXT_PUBLIC_API_BASE_URL,\n")
	buf.WriteString("\twithCredentials: true,\n")
	buf.WriteString("});\n\n")

	// Query Param Interfaces
	buf.WriteString("// ============================================================================\n")
	buf.WriteString("// Query Param Interfaces\n")
	buf.WriteString("// ============================================================================\n\n")
	emitQueryParamInterfaces(&buf, result)

	// Query Keys
	buf.WriteString("// ============================================================================\n")
	buf.WriteString("// Query Keys\n")
	buf.WriteString("// ============================================================================\n\n")
	buf.WriteString("export const queryKeys = {\n")
	emitQueryKeys(&buf, result)
	buf.WriteString("} as const;\n\n")

	// Query Options
	buf.WriteString("// ============================================================================\n")
	buf.WriteString("// Query Options\n")
	buf.WriteString("// ============================================================================\n\n")
	emitQueryOptions(&buf, result)

	// Mutation Functions
	buf.WriteString("// ============================================================================\n")
	buf.WriteString("// Mutation Functions\n")
	buf.WriteString("// ============================================================================\n\n")
	emitMutationFunctions(&buf, result)

	// Mutation Options
	buf.WriteString("// ============================================================================\n")
	buf.WriteString("// Mutation Options\n")
	buf.WriteString("// ============================================================================\n\n")
	emitMutationOptions(&buf, result)

	return buf.String()
}

// collectTypes gathers all TypeScript types needed from @docix/types
func collectTypes(result *ParseResult) map[string]bool {
	types := make(map[string]bool)

	for _, route := range result.Routes {
		handler := lookupHandler(route, result)

		// Add request type if present
		if handler != nil && handler.RequestType != "" {
			types[handler.RequestType] = true
		}

		// Get the response type
		respType := getResponseType(route, handler)

		// Extract types from response type string
		extractTypesFromString(respType, types)
	}

	return types
}

func extractTypesFromString(typeStr string, types map[string]bool) {
	skipTypes := map[string]bool{
		"string":  true,
		"number":  true,
		"boolean": true,
		"null":    true,
		"unknown": true,
	}

	// Handle inline object types like { servers: ServerInfo[] }
	if strings.HasPrefix(typeStr, "{") && strings.HasSuffix(typeStr, "}") {
		// Extract types from inline object properties
		// Pattern: { key: Type[] } or { key: Type; key2: Type2 }
		re := regexp.MustCompile(`:\s*([A-Z][a-zA-Z0-9]*)\s*(?:\[\])?`)
		matches := re.FindAllStringSubmatch(typeStr, -1)
		for _, match := range matches {
			if len(match) > 1 && !skipTypes[match[1]] {
				types[match[1]] = true
			}
		}
		return
	}

	// Remove array brackets
	typeStr = strings.TrimSuffix(typeStr, "[]")

	// Handle generic types like PaginatedResponse<Series>
	if idx := strings.Index(typeStr, "<"); idx != -1 {
		outerType := typeStr[:idx]
		innerType := typeStr[idx+1 : strings.Index(typeStr, ">")]

		if !skipTypes[outerType] && !strings.HasPrefix(outerType, "{") {
			types[outerType] = true
		}
		if !skipTypes[innerType] && !strings.HasPrefix(innerType, "{") {
			types[innerType] = true
		}
		return
	}

	// Handle union types like "Type | null"
	if strings.Contains(typeStr, "|") {
		parts := strings.Split(typeStr, "|")
		for _, part := range parts {
			part = strings.TrimSpace(part)
			if !skipTypes[part] && !strings.HasPrefix(part, "{") {
				types[part] = true
			}
		}
		return
	}

	// Simple type
	if !skipTypes[typeStr] && !strings.HasPrefix(typeStr, "{") && typeStr != "" {
		types[typeStr] = true
	}
}

func lookupHandler(route Route, result *ParseResult) *Handler {
	handlerType := result.HandlerVarToType[route.HandlerVar]
	if handlerType == "" {
		return nil
	}

	key := handlerType + "." + route.HandlerFunc
	if h, ok := result.Handlers[key]; ok {
		return &h
	}

	return nil
}

func getFunctionName(route Route) string {
	baseName := strings.ToLower(route.HandlerFunc[:1]) + route.HandlerFunc[1:]

	if strings.HasPrefix(route.Path, "/admin/") {
		return "admin" + route.HandlerFunc
	}

	return baseName
}

// getResponseType returns the TypeScript response type for a handler
func getResponseType(route Route, handler *Handler) string {
	// Handle cases where the same handler name has different responses based on path
	if route.HandlerFunc == "GetChapter" {
		if strings.HasPrefix(route.Path, "/admin/") {
			return "ChapterWithPages"
		}
		return "ChapterReader"
	}

	// Look up in the explicit mapping first
	if respType, ok := handlerResponseTypes[route.HandlerFunc]; ok {
		return respType
	}

	// Fallback to MessageResponse for unmapped handlers
	return "MessageResponse"
}

func getQueryKeyParts(route Route, handler *Handler) (string, string) {
	funcName := route.HandlerFunc
	isAdmin := strings.HasPrefix(route.Path, "/admin/")

	var keyName string
	hasPathParam := handler != nil && len(handler.PathParams) > 0
	hasQueryParams := handler != nil && len(handler.QueryParams) > 0

	if strings.HasPrefix(funcName, "Get") && hasPathParam {
		baseName := funcName[3:]
		keyName = strings.ToLower(baseName[:1]) + baseName[1:] + "Detail"
	} else if strings.HasPrefix(funcName, "Get") {
		baseName := funcName[3:]
		keyName = strings.ToLower(baseName[:1]) + baseName[1:]
	} else if strings.HasPrefix(funcName, "List") {
		baseName := funcName[4:]
		keyName = strings.ToLower(baseName[:1]) + baseName[1:]
	} else {
		keyName = strings.ToLower(funcName[:1]) + funcName[1:]
	}

	if isAdmin {
		keyName = "admin" + strings.ToUpper(keyName[:1]) + keyName[1:]
	}

	segments := getPathSegments(route.Path)
	keyParts := make([]string, 0)
	for _, s := range segments {
		if !strings.HasPrefix(s, "{") {
			keyParts = append(keyParts, fmt.Sprintf(`"%s"`, s))
		}
	}

	// Handle different combinations of path params and query params
	if hasPathParam && hasQueryParams {
		params := handler.PathParams
		paramName := params[0]
		paramsInterface := getQueryParamsInterfaceName(route)
		return fmt.Sprintf("%s: (%s: string, params?: %s) => [%s, \"%s\", %s, params] as const",
			keyName, paramName, paramsInterface, strings.Join(keyParts, ", "), keyName, paramName), ""
	} else if hasPathParam {
		params := handler.PathParams
		paramName := params[0]
		return fmt.Sprintf("%s: (%s: string) => [%s, \"%s\", %s] as const",
			keyName, paramName, strings.Join(keyParts, ", "), keyName, paramName), ""
	} else if hasQueryParams {
		paramsInterface := getQueryParamsInterfaceName(route)
		return fmt.Sprintf("%s: (params?: %s) => [%s, params] as const",
			keyName, paramsInterface, strings.Join(keyParts, ", ")), ""
	}

	return keyName, fmt.Sprintf("[%s] as const", strings.Join(keyParts, ", "))
}

// getPathSegments splits a path into segments.
func getPathSegments(path string) []string {
	parts := strings.Split(path, "/")
	result := make([]string, 0)
	for _, p := range parts {
		if p != "" {
			result = append(result, p)
		}
	}
	return result
}

// convertPathToTemplate converts a path with {params} to a template string.
func convertPathToTemplate(path string) string {
	if !strings.Contains(path, "{") {
		return fmt.Sprintf(`"%s"`, path)
	}

	// Convert {param} to ${param}
	re := regexp.MustCompile(`\{(\w+)\}`)
	result := re.ReplaceAllString(path, "${$1}")
	return fmt.Sprintf("`%s`", result)
}

// emitQueryParamInterfaces generates TypeScript interfaces for query parameters.
func emitQueryParamInterfaces(buf *bytes.Buffer, result *ParseResult) {
	seen := make(map[string]bool)

	for _, route := range result.Routes {
		if route.Method != "GET" {
			continue
		}

		handler := lookupHandler(route, result)
		if handler == nil || len(handler.QueryParams) == 0 {
			continue
		}

		interfaceName := getQueryParamsInterfaceName(route)
		if seen[interfaceName] {
			continue
		}
		seen[interfaceName] = true

		fmt.Fprintf(buf, "export interface %s {\n", interfaceName)
		for _, param := range handler.QueryParams {
			fmt.Fprintf(buf, "\t%s?: %s;\n", param.Name, param.Type)
		}
		buf.WriteString("}\n\n")
	}
}

// getQueryParamsInterfaceName generates the TypeScript interface name for query params.
func getQueryParamsInterfaceName(route Route) string {
	isAdmin := strings.HasPrefix(route.Path, "/admin/")
	baseName := route.HandlerFunc

	if isAdmin {
		return "Admin" + baseName + "Params"
	}

	return baseName + "Params"
}
