// Code generated by tygo. DO NOT EDIT.

//////////
// source: models.go

export interface User {
  id: string;
  email: string;
  username?: string;
  avatar?: string;
  roles?: Role[];
  verified_at?: string;
  is_banned: boolean;
  ban_reason?: string;
  banned_at?: string;
  created_at: string;
  updated_at: string;
}
export interface Session {
  id: string;
  user_id: string;
  ip_address: string;
  user_agent: string;
  expires_at: string;
  created_at: string;
}
export interface Role {
  id: string;
  name: string;
  display_name: string;
  description: string;
  color: string;
  priority: number /* int */;
  permissions: string[];
  is_system: boolean;
  created_at: string;
  updated_at: string;
}
export interface SignUpRequest {
  email: string;
  password: string;
  username: string;
}
export interface SignInRequest {
  email: string;
  password: string;
}
export interface AuthResponse {
  message: string;
  user?: User;
}
/**
 * MessageResponse is a generic response with just a message
 */
export interface MessageResponse {
  message: string;
}
/**
 * CurrentSessionResponse is returned when getting the current session
 */
export interface CurrentSessionResponse {
  session: SessionListItem;
  user: User;
  permissions: string[];
  roles: string[];
}
/**
 * UserPermissionsResponse is returned when getting user permissions
 */
export interface UserPermissionsResponse {
  permissions: string[];
  roles: string[];
}
/**
 * UpdateUserResponse is returned when updating user profile
 */
export interface UpdateUserResponse {
  message: string;
  email_verification_required?: boolean;
  email_verification_token?: string;
}
/**
 * RequestVerificationResponse is returned when requesting email verification
 */
export interface RequestVerificationResponse {
  message: string;
  token: string;
}
/**
 * BookmarkStatusResponse is returned when checking bookmark status
 */
export interface BookmarkStatusResponse {
  bookmarked: boolean;
  bookmark_id?: string;
}
/**
 * ToggleBookmarkResponse is returned when toggling a bookmark
 */
export interface ToggleBookmarkResponse {
  bookmarked: boolean;
  bookmark_id?: string;
  message: string;
}
/**
 * HealthResponse is returned by the health check endpoint
 */
export interface HealthResponse {
  status: string;
}
export interface ErrorResponse {
  error: string;
  message: string;
}
export interface SessionListItem {
  id: string;
  ip_address: string;
  user_agent: string;
  expires_at: string;
  created_at: string;
  is_current: boolean;
}
export interface RevokeSessionRequest {
  session_id: string;
}
export interface CreateRoleRequest {
  name: string;
  display_name: string;
  description: string;
  color: string;
  priority: number /* int */;
  permissions: string[];
}
export interface UpdateRoleRequest {
  display_name?: string;
  description?: string;
  color?: string;
  priority?: number /* int */;
  permissions?: string[];
}
export interface AssignRoleRequest {
  user_id: string;
  role_id: string;
}
export interface BanUserRequest {
  user_id: string;
  reason: string;
}
export interface UpdateUserRequest {
  email?: string;
  username?: string;
}
export interface VerifyEmailRequest {
  token: string;
}
export interface ChangePasswordRequest {
  current_password: string;
  new_password: string;
}
export type SeriesStatus = string;
export const SeriesStatusOngoing: SeriesStatus = "ongoing";
export const SeriesStatusCompleted: SeriesStatus = "completed";
export const SeriesStatusHiatus: SeriesStatus = "hiatus";
export const SeriesStatusCancelled: SeriesStatus = "cancelled";
export interface Tag {
  id: string;
  name: string;
  slug: string;
  description?: string;
  created_at: string;
  updated_at: string;
}
export interface Series {
  id: string;
  title: string;
  slug: string;
  description?: string;
  cover_image?: string;
  cover_image_url?: string; // Signed URL (not stored in DB)
  author?: string;
  artist?: string;
  status: SeriesStatus;
  tags?: Tag[];
  view_count: number /* int64 */;
  chapter_count: number /* int */;
  created_at: string;
  updated_at: string;
}
export interface Chapter {
  id: string;
  series_id: string;
  number: number /* float64 */;
  title?: string;
  page_count: number /* int */;
  view_count: number /* int64 */;
  created_at: string;
  updated_at: string;
}
export interface Page {
  id: string;
  chapter_id: string;
  number: number /* int */;
  image_url: string;
  image_url_signed?: string; // Signed URL (not stored in DB)
  created_at: string;
}
export interface Bookmark {
  id: string;
  user_id: string;
  series_id: string;
  created_at: string;
}
export interface CreateTagRequest {
  name: string;
  description: string;
}
export interface UpdateTagRequest {
  name?: string;
  description?: string;
}
export interface CreateSeriesRequest {
  title: string;
  description: string;
  cover_image: string;
  author: string;
  artist: string;
  status: string;
  tag_ids: string[];
}
export interface UpdateSeriesRequest {
  title?: string;
  description?: string;
  cover_image?: string;
  author?: string;
  artist?: string;
  status?: string;
  tag_ids?: string[];
}
export interface ListSeriesRequest {
  page: number /* int */;
  limit: number /* int */;
  status: string;
  search: string;
  sort_by: string;
  order: string;
}
export interface PaginatedResponse<T extends any> {
  data: T[];
  total: number /* int64 */;
  page: number /* int */;
  limit: number /* int */;
  total_pages: number /* int */;
}
export interface CreateChapterRequest {
  number: number /* float64 */;
  title: string;
}
export interface UpdateChapterRequest {
  number?: number /* float64 */;
  title?: string;
}
export interface ChapterWithPages {
  id: string;
  series_id: string;
  number: number /* float64 */;
  title?: string;
  page_count: number /* int */;
  view_count: number /* int64 */;
  created_at: string;
  updated_at: string;
  pages?: Page[];
}
export interface CreatePagesRequest {
  pages: CreatePageItem[];
}
export interface CreatePageItem {
  number: number /* int */;
  image_url: string; // Filename only (e.g., "uuid.webp")
}
export interface UpdatePageRequest {
  number?: number /* int */;
}
export interface ReorderPagesRequest {
  page_orders: PageOrder[];
}
export interface PageOrder {
  page_id: string;
  number: number /* int */;
}
export interface UploadResponse {
  url: string;
  filename: string;
}
/**
 * AsyncUploadResponse is returned when an upload is queued for processing
 */
export interface AsyncUploadResponse {
  upload_id: string;
  status: string;
}
/**
 * AsyncBulkUploadResponse is returned when multiple uploads are queued
 */
export interface AsyncBulkUploadResponse {
  uploads: AsyncUploadResponse[];
  failed?: string[];
}
/**
 * UploadStatusResponse is returned when checking upload status
 */
export interface UploadStatusResponse {
  upload_id: string;
  status: string;
  filename?: string;
  error?: string;
  width?: number /* int */;
  height?: number /* int */;
  size?: number /* int64 */;
}
export interface BulkUploadResponse {
  uploads: UploadResponse[];
  failed?: string[];
}
export interface SeriesWithChapters {
  series: Series;
  chapters: Chapter[];
}
export interface ChapterNav {
  id: string;
  number: number /* float64 */;
  title?: string;
}
export interface ChapterReader {
  chapter: Chapter;
  series_slug: string;
  series_title: string;
  total_chapters: number /* int */;
  pages: Page[];
  prev_chapter?: ChapterNav;
  next_chapter?: ChapterNav;
}
/**
 * DashboardStats provides aggregate statistics for the admin dashboard
 */
export interface DashboardStats {
  /**
   * Core counts
   */
  total_users: number /* int64 */;
  total_series: number /* int64 */;
  total_chapters: number /* int64 */;
  total_views: number /* int64 */;
  /**
   * User breakdown
   */
  verified_users: number /* int64 */;
  banned_users: number /* int64 */;
  /**
   * Series by status for pie chart
   */
  series_by_status: { [key: string]: number /* int64 */};
  /**
   * Time-series data for charts (last 7 days)
   */
  user_registrations: DailyCount[];
  chapter_uploads: DailyCount[];
  /**
   * Top content
   */
  top_series_by_views: SeriesViewCount[];
  /**
   * Recent activity
   */
  recent_series: Series[];
  recent_users: User[];
}
/**
 * DailyCount represents a count for a specific date
 */
export interface DailyCount {
  date: string; // YYYY-MM-DD format
  count: number /* int64 */;
}
/**
 * SeriesViewCount represents a series with its view count for ranking
 */
export interface SeriesViewCount {
  id: string;
  title: string;
  view_count: number /* int64 */;
}
/**
 * SiteSettings stores all configurable site settings
 * There should only be one document in the settings collection
 */
export interface SiteSettings {
  id: string;
  site: SiteConfig;
  content: ContentConfig;
  users: UserConfig;
  integrations: IntegrationsConfig;
  maintenance: MaintenanceConfig;
  updated_at: string;
}
/**
 * SiteConfig contains general site configuration
 */
export interface SiteConfig {
  name: string;
  description: string;
  logo_url: string;
  favicon_url: string;
  default_locale: string;
  meta_title: string;
  meta_description: string;
}
/**
 * ContentConfig contains content-related settings
 */
export interface ContentConfig {
  max_upload_size_mb: number /* int */;
  max_chapters_per_day: number /* int */;
  allowed_image_types: string; // Comma-separated: jpg,png,webp
  default_content_rating: string;
  enable_comments: boolean;
  require_moderation: boolean;
}
/**
 * UserConfig contains user-related settings
 */
export interface UserConfig {
  registration_open: boolean;
  require_email_verification: boolean;
  default_role_id: string;
  allow_username_change: boolean;
  min_password_length: number /* int */;
  max_login_attempts: number /* int */;
}
/**
 * IntegrationsConfig contains external service configurations
 */
export interface IntegrationsConfig {
  smtp_host: string;
  smtp_port: number /* int */;
  smtp_username: string;
  smtp_from_email: string;
  smtp_from_name: string;
  smtp_enabled: boolean;
  cdn_enabled: boolean;
  cdn_base_url: string;
}
/**
 * MaintenanceConfig contains maintenance mode settings
 */
export interface MaintenanceConfig {
  enabled: boolean;
  message: string;
  allowed_ips: string; // Comma-separated IPs
  scheduled_start?: string;
  scheduled_end?: string;
}
/**
 * UpdateSiteSettingsRequest is the request body for updating site settings
 */
export interface UpdateSiteSettingsRequest {
  site?: SiteConfig;
  content?: ContentConfig;
  users?: UserConfig;
  integrations?: UpdateIntegrationsRequest;
  maintenance?: MaintenanceConfig;
}
/**
 * UpdateIntegrationsRequest allows partial SMTP password updates
 */
export interface UpdateIntegrationsRequest {
  smtp_host?: string;
  smtp_port?: number /* int */;
  smtp_username?: string;
  smtp_password?: string; // Only set if changing
  smtp_from_email?: string;
  smtp_from_name?: string;
  smtp_enabled?: boolean;
  cdn_enabled?: boolean;
  cdn_base_url?: string;
}
/**
 * MaintenanceAction represents actions that can be performed
 */
export interface MaintenanceAction {
  action: string;
}
/**
 * MaintenanceActionResponse is the response for maintenance actions
 */
export interface MaintenanceActionResponse {
  success: boolean;
  message: string;
}
/**
 * CacheStats provides information about cache usage
 */
export interface CacheStats {
  redis_connected: boolean;
  key_count: number /* int64 */;
  memory_usage: string;
}
/**
 * SystemInfo provides system status information
 */
export interface SystemInfo {
  version: string;
  go_version: string;
  uptime: string;
  database_status: string;
  cache_stats: CacheStats;
}
