// Code generated by @docix/codegen. DO NOT EDIT.
// Run `pnpm generate` to regenerate this file.

import type {
	AssignRoleRequest,
	AuthResponse,
	BanUserRequest,
	ChangePasswordRequest,
	Chapter,
	ChapterWithPages,
	CreateChapterRequest,
	CreatePagesRequest,
	CreateRoleRequest,
	CreateSeriesRequest,
	CreateTagRequest,
	PaginatedResponse,
	ReorderPagesRequest,
	RevokeSessionRequest,
	Role,
	Series,
	SessionListItem,
	SignInRequest,
	SignUpRequest,
	Tag,
	UpdateChapterRequest,
	UpdatePageRequest,
	UpdateRoleRequest,
	UpdateSeriesRequest,
	UpdateTagRequest,
	UpdateUserRequest,
	User,
	VerifyEmailRequest,
} from "@docix/types";
import { mutationOptions, queryOptions } from "@tanstack/react-query";
import axios, { type AxiosRequestConfig } from "axios";

export const api = axios.create({
	baseURL: process.env.NEXT_PUBLIC_API_BASE_URL,
	withCredentials: true,
});

// ============================================================================
// Response Types
// ============================================================================

interface MessageResponse {
	message: string;
}

interface CurrentSessionResponse {
	session: SessionListItem;
	user: User;
}

interface UserPermissionsResponse {
	permissions: string[];
	roles: string[];
}

interface UpdateUserResponse {
	message: string;
	email_verification_required?: boolean;
	email_verification_token?: string;
}

interface RequestVerificationResponse {
	message: string;
	token: string;
}

// ============================================================================
// Query Keys
// ============================================================================

export const queryKeys = {
	health: ["health"] as const,
	currentSession: ["auth", "session"] as const,
	sessions: ["auth", "sessions"] as const,
	userPermissions: ["auth", "permissions"] as const,
	permissions: ["admin", "permissions"] as const,
	roles: ["admin", "roles"] as const,
	roleDetail: (id: string) => ["admin", "roles", "roleDetail", id] as const,
	users: ["admin", "users"] as const,
	tags: ["admin", "tags"] as const,
	series: ["admin", "series"] as const,
	seriesDetail: (id: string) =>
		["admin", "series", "seriesDetail", id] as const,
	chapters: (id: string) =>
		["admin", "series", "chapters", "chapters", id] as const,
	chapterDetail: (id: string) =>
		["admin", "chapters", "chapterDetail", id] as const,
} as const;

// ============================================================================
// Query Options
// ============================================================================

export const getHealthQueryOptions = (config?: AxiosRequestConfig) =>
	queryOptions({
		queryKey: queryKeys.health,
		queryFn: async () => {
			const { data } = await api.get<{ status: string }>("/health", config);
			return data;
		},
	});

export const getCurrentSessionQueryOptions = (config?: AxiosRequestConfig) =>
	queryOptions({
		queryKey: queryKeys.currentSession,
		queryFn: async () => {
			const { data } = await api.get<CurrentSessionResponse | null>(
				"/auth/session",
				config,
			);
			return data;
		},
	});

export const listSessionsQueryOptions = (config?: AxiosRequestConfig) =>
	queryOptions({
		queryKey: queryKeys.sessions,
		queryFn: async () => {
			const { data } = await api.get<SessionListItem[]>(
				"/auth/sessions",
				config,
			);
			return data;
		},
	});

export const getUserPermissionsQueryOptions = (config?: AxiosRequestConfig) =>
	queryOptions({
		queryKey: queryKeys.userPermissions,
		queryFn: async () => {
			const { data } = await api.get<UserPermissionsResponse>(
				"/auth/permissions",
				config,
			);
			return data;
		},
	});

export const getPermissionsQueryOptions = (config?: AxiosRequestConfig) =>
	queryOptions({
		queryKey: queryKeys.permissions,
		queryFn: async () => {
			const { data } = await api.get<string[]>("/admin/permissions", config);
			return data;
		},
	});

export const listRolesQueryOptions = (config?: AxiosRequestConfig) =>
	queryOptions({
		queryKey: queryKeys.roles,
		queryFn: async () => {
			const { data } = await api.get<Role[]>("/admin/roles", config);
			return data;
		},
	});

export const getRoleQueryOptions = (id: string, config?: AxiosRequestConfig) =>
	queryOptions({
		queryKey: queryKeys.roleDetail(id),
		queryFn: async () => {
			const { data } = await api.get<Role>(`/admin/roles/${id}`, config);
			return data;
		},
		enabled: !!id,
	});

export const listUsersQueryOptions = (config?: AxiosRequestConfig) =>
	queryOptions({
		queryKey: queryKeys.users,
		queryFn: async () => {
			const { data } = await api.get<User[]>("/admin/users", config);
			return data;
		},
	});

export const listTagsQueryOptions = (config?: AxiosRequestConfig) =>
	queryOptions({
		queryKey: queryKeys.tags,
		queryFn: async () => {
			const { data } = await api.get<Tag[]>("/admin/tags", config);
			return data;
		},
	});

export const listSeriesQueryOptions = (config?: AxiosRequestConfig) =>
	queryOptions({
		queryKey: queryKeys.series,
		queryFn: async () => {
			const { data } = await api.get<PaginatedResponse<Series>>(
				"/admin/series",
				config,
			);
			return data;
		},
	});

export const getSeriesQueryOptions = (
	id: string,
	config?: AxiosRequestConfig,
) =>
	queryOptions({
		queryKey: queryKeys.seriesDetail(id),
		queryFn: async () => {
			const { data } = await api.get<Series>(`/admin/series/${id}`, config);
			return data;
		},
		enabled: !!id,
	});

export const listChaptersQueryOptions = (
	id: string,
	config?: AxiosRequestConfig,
) =>
	queryOptions({
		queryKey: queryKeys.chapters(id),
		queryFn: async () => {
			const { data } = await api.get<Chapter[]>(
				`/admin/series/${id}/chapters`,
				config,
			);
			return data;
		},
		enabled: !!id,
	});

export const getChapterQueryOptions = (
	id: string,
	config?: AxiosRequestConfig,
) =>
	queryOptions({
		queryKey: queryKeys.chapterDetail(id),
		queryFn: async () => {
			const { data } = await api.get<ChapterWithPages>(
				`/admin/chapters/${id}`,
				config,
			);
			return data;
		},
		enabled: !!id,
	});

// ============================================================================
// Mutation Functions
// ============================================================================

export const signUp = async (
	request: SignUpRequest,
	config?: AxiosRequestConfig,
) => {
	const { data } = await api.post<MessageResponse>(
		"/auth/sign-up",
		request,
		config,
	);
	return data;
};

export const signIn = async (
	request: SignInRequest,
	config?: AxiosRequestConfig,
) => {
	const { data } = await api.post<AuthResponse>(
		"/auth/sign-in",
		request,
		config,
	);
	return data;
};

export const signOut = async (config?: AxiosRequestConfig) => {
	const { data } = await api.post<MessageResponse>(
		"/auth/sign-out",
		undefined,
		config,
	);
	return data;
};

export const verifyEmail = async (
	request: VerifyEmailRequest,
	config?: AxiosRequestConfig,
) => {
	const { data } = await api.post<MessageResponse>(
		"/auth/verify-email",
		request,
		config,
	);
	return data;
};

export const updateUser = async (
	request: UpdateUserRequest,
	config?: AxiosRequestConfig,
) => {
	const { data } = await api.patch<UpdateUserResponse>(
		"/auth/update-user",
		request,
		config,
	);
	return data;
};

export const changePassword = async (
	request: ChangePasswordRequest,
	config?: AxiosRequestConfig,
) => {
	const { data } = await api.post<MessageResponse>(
		"/auth/change-password",
		request,
		config,
	);
	return data;
};

export const requestEmailVerification = async (config?: AxiosRequestConfig) => {
	const { data } = await api.post<RequestVerificationResponse>(
		"/auth/request-verification",
		undefined,
		config,
	);
	return data;
};

export const revokeSession = async (
	request: RevokeSessionRequest,
	config?: AxiosRequestConfig,
) => {
	const { data } = await api.delete<MessageResponse>("/auth/sessions", {
		...config,
		data: request,
	});
	return data;
};

export const incrementSeriesView = async (
	id: string,
	config?: AxiosRequestConfig,
) => {
	const { data } = await api.post<MessageResponse>(
		`/series/${id}/view`,
		undefined,
		config,
	);
	return data;
};

export const incrementChapterView = async (
	id: string,
	config?: AxiosRequestConfig,
) => {
	const { data } = await api.post<MessageResponse>(
		`/chapters/${id}/view`,
		undefined,
		config,
	);
	return data;
};

export const createRole = async (
	request: CreateRoleRequest,
	config?: AxiosRequestConfig,
) => {
	const { data } = await api.post<Role>("/admin/roles", request, config);
	return data;
};

export const updateRole = async (
	id: string,
	request: UpdateRoleRequest,
	config?: AxiosRequestConfig,
) => {
	const { data } = await api.patch<MessageResponse>(
		`/admin/roles/${id}`,
		request,
		config,
	);
	return data;
};

export const deleteRole = async (id: string, config?: AxiosRequestConfig) => {
	const { data } = await api.delete<MessageResponse>(
		`/admin/roles/${id}`,
		config,
	);
	return data;
};

export const assignRole = async (
	request: AssignRoleRequest,
	config?: AxiosRequestConfig,
) => {
	const { data } = await api.post<MessageResponse>(
		"/admin/roles/assign",
		request,
		config,
	);
	return data;
};

export const removeRole = async (
	request: AssignRoleRequest,
	config?: AxiosRequestConfig,
) => {
	const { data } = await api.post<MessageResponse>(
		"/admin/roles/remove",
		request,
		config,
	);
	return data;
};

export const banUser = async (
	request: BanUserRequest,
	config?: AxiosRequestConfig,
) => {
	const { data } = await api.post<MessageResponse>(
		"/admin/users/ban",
		request,
		config,
	);
	return data;
};

export const unbanUser = async (id: string, config?: AxiosRequestConfig) => {
	const { data } = await api.post<MessageResponse>(
		`/admin/users/unban/${id}`,
		undefined,
		config,
	);
	return data;
};

export const createTag = async (
	request: CreateTagRequest,
	config?: AxiosRequestConfig,
) => {
	const { data } = await api.post<Tag>("/admin/tags", request, config);
	return data;
};

export const updateTag = async (
	id: string,
	request: UpdateTagRequest,
	config?: AxiosRequestConfig,
) => {
	const { data } = await api.patch<MessageResponse>(
		`/admin/tags/${id}`,
		request,
		config,
	);
	return data;
};

export const deleteTag = async (id: string, config?: AxiosRequestConfig) => {
	const { data } = await api.delete<MessageResponse>(
		`/admin/tags/${id}`,
		config,
	);
	return data;
};

export const createSeries = async (
	request: CreateSeriesRequest,
	config?: AxiosRequestConfig,
) => {
	const { data } = await api.post<Series>("/admin/series", request, config);
	return data;
};

export const updateSeries = async (
	id: string,
	request: UpdateSeriesRequest,
	config?: AxiosRequestConfig,
) => {
	const { data } = await api.patch<Series>(
		`/admin/series/${id}`,
		request,
		config,
	);
	return data;
};

export const deleteSeries = async (id: string, config?: AxiosRequestConfig) => {
	const { data } = await api.delete<MessageResponse>(
		`/admin/series/${id}`,
		config,
	);
	return data;
};

export const createChapter = async (
	id: string,
	request: CreateChapterRequest,
	config?: AxiosRequestConfig,
) => {
	const { data } = await api.post<Chapter>(
		`/admin/series/${id}/chapters`,
		request,
		config,
	);
	return data;
};

export const updateChapter = async (
	id: string,
	request: UpdateChapterRequest,
	config?: AxiosRequestConfig,
) => {
	const { data } = await api.patch<MessageResponse>(
		`/admin/chapters/${id}`,
		request,
		config,
	);
	return data;
};

export const deleteChapter = async (
	id: string,
	config?: AxiosRequestConfig,
) => {
	const { data } = await api.delete<MessageResponse>(
		`/admin/chapters/${id}`,
		config,
	);
	return data;
};

export const addPages = async (
	id: string,
	request: CreatePagesRequest,
	config?: AxiosRequestConfig,
) => {
	const { data } = await api.post<MessageResponse>(
		`/admin/chapters/${id}/pages`,
		request,
		config,
	);
	return data;
};

export const reorderPages = async (
	id: string,
	request: ReorderPagesRequest,
	config?: AxiosRequestConfig,
) => {
	const { data } = await api.post<MessageResponse>(
		`/admin/chapters/${id}/pages/reorder`,
		request,
		config,
	);
	return data;
};

export const updatePage = async (
	id: string,
	request: UpdatePageRequest,
	config?: AxiosRequestConfig,
) => {
	const { data } = await api.patch<MessageResponse>(
		`/admin/pages/${id}`,
		request,
		config,
	);
	return data;
};

export const deletePage = async (id: string, config?: AxiosRequestConfig) => {
	const { data } = await api.delete<MessageResponse>(
		`/admin/pages/${id}`,
		config,
	);
	return data;
};

// ============================================================================
// Mutation Options
// ============================================================================

export const signUpMutationOptions = (config?: AxiosRequestConfig) =>
	mutationOptions({
		mutationFn: (request: SignUpRequest) => signUp(request, config),
	});

export const signInMutationOptions = (config?: AxiosRequestConfig) =>
	mutationOptions({
		mutationFn: (request: SignInRequest) => signIn(request, config),
	});

export const signOutMutationOptions = (config?: AxiosRequestConfig) =>
	mutationOptions({
		mutationFn: () => signOut(config),
	});

export const verifyEmailMutationOptions = (config?: AxiosRequestConfig) =>
	mutationOptions({
		mutationFn: (request: VerifyEmailRequest) => verifyEmail(request, config),
	});

export const updateUserMutationOptions = (config?: AxiosRequestConfig) =>
	mutationOptions({
		mutationFn: (request: UpdateUserRequest) => updateUser(request, config),
	});

export const changePasswordMutationOptions = (config?: AxiosRequestConfig) =>
	mutationOptions({
		mutationFn: (request: ChangePasswordRequest) =>
			changePassword(request, config),
	});

export const requestEmailVerificationMutationOptions = (
	config?: AxiosRequestConfig,
) =>
	mutationOptions({
		mutationFn: () => requestEmailVerification(config),
	});

export const revokeSessionMutationOptions = (config?: AxiosRequestConfig) =>
	mutationOptions({
		mutationFn: (request: RevokeSessionRequest) =>
			revokeSession(request, config),
	});

export const incrementSeriesViewMutationOptions = (
	config?: AxiosRequestConfig,
) =>
	mutationOptions({
		mutationFn: (id: string) => incrementSeriesView(id, config),
	});

export const incrementChapterViewMutationOptions = (
	config?: AxiosRequestConfig,
) =>
	mutationOptions({
		mutationFn: (id: string) => incrementChapterView(id, config),
	});

export const createRoleMutationOptions = (config?: AxiosRequestConfig) =>
	mutationOptions({
		mutationFn: (request: CreateRoleRequest) => createRole(request, config),
	});

export const updateRoleMutationOptions = (config?: AxiosRequestConfig) =>
	mutationOptions({
		mutationFn: ({ id, ...request }: { id: string } & UpdateRoleRequest) =>
			updateRole(id, request, config),
	});

export const deleteRoleMutationOptions = (config?: AxiosRequestConfig) =>
	mutationOptions({
		mutationFn: (id: string) => deleteRole(id, config),
	});

export const assignRoleMutationOptions = (config?: AxiosRequestConfig) =>
	mutationOptions({
		mutationFn: (request: AssignRoleRequest) => assignRole(request, config),
	});

export const removeRoleMutationOptions = (config?: AxiosRequestConfig) =>
	mutationOptions({
		mutationFn: (request: AssignRoleRequest) => removeRole(request, config),
	});

export const banUserMutationOptions = (config?: AxiosRequestConfig) =>
	mutationOptions({
		mutationFn: (request: BanUserRequest) => banUser(request, config),
	});

export const unbanUserMutationOptions = (config?: AxiosRequestConfig) =>
	mutationOptions({
		mutationFn: (id: string) => unbanUser(id, config),
	});

export const createTagMutationOptions = (config?: AxiosRequestConfig) =>
	mutationOptions({
		mutationFn: (request: CreateTagRequest) => createTag(request, config),
	});

export const updateTagMutationOptions = (config?: AxiosRequestConfig) =>
	mutationOptions({
		mutationFn: ({ id, ...request }: { id: string } & UpdateTagRequest) =>
			updateTag(id, request, config),
	});

export const deleteTagMutationOptions = (config?: AxiosRequestConfig) =>
	mutationOptions({
		mutationFn: (id: string) => deleteTag(id, config),
	});

export const createSeriesMutationOptions = (config?: AxiosRequestConfig) =>
	mutationOptions({
		mutationFn: (request: CreateSeriesRequest) => createSeries(request, config),
	});

export const updateSeriesMutationOptions = (config?: AxiosRequestConfig) =>
	mutationOptions({
		mutationFn: ({ id, ...request }: { id: string } & UpdateSeriesRequest) =>
			updateSeries(id, request, config),
	});

export const deleteSeriesMutationOptions = (config?: AxiosRequestConfig) =>
	mutationOptions({
		mutationFn: (id: string) => deleteSeries(id, config),
	});

export const createChapterMutationOptions = (config?: AxiosRequestConfig) =>
	mutationOptions({
		mutationFn: ({ id, ...request }: { id: string } & CreateChapterRequest) =>
			createChapter(id, request, config),
	});

export const updateChapterMutationOptions = (config?: AxiosRequestConfig) =>
	mutationOptions({
		mutationFn: ({ id, ...request }: { id: string } & UpdateChapterRequest) =>
			updateChapter(id, request, config),
	});

export const deleteChapterMutationOptions = (config?: AxiosRequestConfig) =>
	mutationOptions({
		mutationFn: (id: string) => deleteChapter(id, config),
	});

export const addPagesMutationOptions = (config?: AxiosRequestConfig) =>
	mutationOptions({
		mutationFn: ({ id, ...request }: { id: string } & CreatePagesRequest) =>
			addPages(id, request, config),
	});

export const reorderPagesMutationOptions = (config?: AxiosRequestConfig) =>
	mutationOptions({
		mutationFn: ({ id, ...request }: { id: string } & ReorderPagesRequest) =>
			reorderPages(id, request, config),
	});

export const updatePageMutationOptions = (config?: AxiosRequestConfig) =>
	mutationOptions({
		mutationFn: ({ id, ...request }: { id: string } & UpdatePageRequest) =>
			updatePage(id, request, config),
	});

export const deletePageMutationOptions = (config?: AxiosRequestConfig) =>
	mutationOptions({
		mutationFn: (id: string) => deletePage(id, config),
	});
