// Code generated by @docix/codegen. DO NOT EDIT.
// Run `pnpm generate` to regenerate this file.

import type {
	AssignRoleRequest,
	AsyncBulkUploadResponse,
	AsyncUploadResponse,
	AuthResponse,
	BanUserRequest,
	Bookmark,
	BookmarkStatusResponse,
	ChangePasswordRequest,
	Chapter,
	ChapterReader,
	ChapterWithPages,
	CreateChapterRequest,
	CreatePagesRequest,
	CreateRoleRequest,
	CreateSeriesRequest,
	CreateTagRequest,
	CurrentSessionResponse,
	DashboardStats,
	HealthResponse,
	MaintenanceAction,
	MaintenanceActionResponse,
	MessageResponse,
	Page,
	PaginatedResponse,
	ReorderPagesRequest,
	RequestVerificationResponse,
	RevokeSessionRequest,
	Role,
	Series,
	SeriesWithChapters,
	SessionListItem,
	SignInRequest,
	SignUpRequest,
	SiteSettings,
	SystemInfo,
	Tag,
	ToggleBookmarkResponse,
	UpdateChapterRequest,
	UpdatePageRequest,
	UpdateRoleRequest,
	UpdateSeriesRequest,
	UpdateSiteSettingsRequest,
	UpdateTagRequest,
	UpdateUserRequest,
	UpdateUserResponse,
	UploadStatusResponse,
	User,
	UserPermissionsResponse,
	VerifyEmailRequest,
} from "@docix/types";
import { mutationOptions, queryOptions } from "@tanstack/react-query";
import axios, { type AxiosRequestConfig } from "axios";

export const api = axios.create({
	baseURL: process.env.NEXT_PUBLIC_API_BASE_URL,
	withCredentials: true,
});

// ============================================================================
// Query Param Interfaces
// ============================================================================

export interface ListSeriesParams {
	page?: number;
	limit?: number;
	status?: string;
	tag?: string;
	search?: string;
	sort?: string;
}

export interface AdminListSeriesParams {
	page?: number;
	limit?: number;
	status?: string;
	search?: string;
	sort_by?: string;
	order?: string;
}

// ============================================================================
// Query Keys
// ============================================================================

export const queryKeys = {
	health: ["health"] as const,
	currentSession: ["auth", "session"] as const,
	sessions: ["auth", "sessions"] as const,
	userPermissions: ["auth", "permissions"] as const,
	bookmarks: ["bookmarks"] as const,
	bookmarkStatusDetail: (seriesId: string) =>
		["bookmarks", "bookmarkStatusDetail", seriesId] as const,
	series: (params?: ListSeriesParams) => ["manga", params] as const,
	seriesBySlugDetail: (slug: string) =>
		["manga", "seriesBySlugDetail", slug] as const,
	chapterDetail: (slug: string) =>
		["manga", "chapters", "chapterDetail", slug] as const,
	tags: ["tags"] as const,
	adminPermissions: ["admin", "permissions"] as const,
	adminDashboardStats: ["admin", "stats"] as const,
	adminUploadStatusDetail: (id: string) =>
		["admin", "upload", "status", "adminUploadStatusDetail", id] as const,
	adminRoles: ["admin", "roles"] as const,
	adminRoleDetail: (id: string) =>
		["admin", "roles", "adminRoleDetail", id] as const,
	adminUsers: ["admin", "users"] as const,
	adminTags: ["admin", "tags"] as const,
	adminSeries: (params?: AdminListSeriesParams) =>
		["admin", "series", params] as const,
	adminSeriesDetail: (id: string) =>
		["admin", "series", "adminSeriesDetail", id] as const,
	adminChapters: (id: string) =>
		["admin", "series", "chapters", "adminChapters", id] as const,
	adminChapterDetail: (id: string) =>
		["admin", "chapters", "adminChapterDetail", id] as const,
	adminSiteSettings: ["admin", "settings"] as const,
	adminSystemInfo: ["admin", "settings", "system"] as const,
} as const;

// ============================================================================
// Query Options
// ============================================================================

export const getHealthQueryOptions = (config?: AxiosRequestConfig) =>
	queryOptions({
		queryKey: queryKeys.health,
		queryFn: async () => {
			const { data } = await api.get<HealthResponse>("/health", config);
			return data;
		},
	});

export const getCurrentSessionQueryOptions = (config?: AxiosRequestConfig) =>
	queryOptions({
		queryKey: queryKeys.currentSession,
		queryFn: async () => {
			const { data } = await api.get<CurrentSessionResponse | null>(
				"/auth/session",
				config,
			);
			return data;
		},
	});

export const listSessionsQueryOptions = (config?: AxiosRequestConfig) =>
	queryOptions({
		queryKey: queryKeys.sessions,
		queryFn: async () => {
			const { data } = await api.get<SessionListItem[]>(
				"/auth/sessions",
				config,
			);
			return data;
		},
	});

export const getUserPermissionsQueryOptions = (config?: AxiosRequestConfig) =>
	queryOptions({
		queryKey: queryKeys.userPermissions,
		queryFn: async () => {
			const { data } = await api.get<UserPermissionsResponse>(
				"/auth/permissions",
				config,
			);
			return data;
		},
	});

export const listBookmarksQueryOptions = (config?: AxiosRequestConfig) =>
	queryOptions({
		queryKey: queryKeys.bookmarks,
		queryFn: async () => {
			const { data } = await api.get<Bookmark[]>("/bookmarks", config);
			return data;
		},
	});

export const getBookmarkStatusQueryOptions = (
	seriesId: string,
	config?: AxiosRequestConfig,
) =>
	queryOptions({
		queryKey: queryKeys.bookmarkStatusDetail(seriesId),
		queryFn: async () => {
			const { data } = await api.get<BookmarkStatusResponse>(
				`/bookmarks/${seriesId}`,
				config,
			);
			return data;
		},
		enabled: !!seriesId,
	});

export const listSeriesQueryOptions = (
	params?: ListSeriesParams,
	config?: AxiosRequestConfig,
) =>
	queryOptions({
		queryKey: queryKeys.series(params),
		queryFn: async () => {
			const { data } = await api.get<PaginatedResponse<Series>>("/manga", {
				...config,
				params,
			});
			return data;
		},
	});

export const getSeriesBySlugQueryOptions = (
	slug: string,
	config?: AxiosRequestConfig,
) =>
	queryOptions({
		queryKey: queryKeys.seriesBySlugDetail(slug),
		queryFn: async () => {
			const { data } = await api.get<SeriesWithChapters>(
				`/manga/${slug}`,
				config,
			);
			return data;
		},
		enabled: !!slug,
	});

export const getChapterQueryOptions = (
	slug: string,
	number: string,
	config?: AxiosRequestConfig,
) =>
	queryOptions({
		queryKey: queryKeys.chapterDetail(slug),
		queryFn: async () => {
			const { data } = await api.get<ChapterReader>(
				`/manga/${slug}/chapters/${number}`,
				config,
			);
			return data;
		},
		enabled: !!slug,
	});

export const listTagsQueryOptions = (config?: AxiosRequestConfig) =>
	queryOptions({
		queryKey: queryKeys.tags,
		queryFn: async () => {
			const { data } = await api.get<Tag[]>("/tags", config);
			return data;
		},
	});

export const adminGetPermissionsQueryOptions = (config?: AxiosRequestConfig) =>
	queryOptions({
		queryKey: queryKeys.adminPermissions,
		queryFn: async () => {
			const { data } = await api.get<string[]>("/admin/permissions", config);
			return data;
		},
	});

export const adminGetDashboardStatsQueryOptions = (
	config?: AxiosRequestConfig,
) =>
	queryOptions({
		queryKey: queryKeys.adminDashboardStats,
		queryFn: async () => {
			const { data } = await api.get<DashboardStats>("/admin/stats", config);
			return data;
		},
	});

export const adminGetUploadStatusQueryOptions = (
	id: string,
	config?: AxiosRequestConfig,
) =>
	queryOptions({
		queryKey: queryKeys.adminUploadStatusDetail(id),
		queryFn: async () => {
			const { data } = await api.get<UploadStatusResponse>(
				`/admin/upload/${id}/status`,
				config,
			);
			return data;
		},
		enabled: !!id,
	});

export const adminListRolesQueryOptions = (config?: AxiosRequestConfig) =>
	queryOptions({
		queryKey: queryKeys.adminRoles,
		queryFn: async () => {
			const { data } = await api.get<Role[]>("/admin/roles", config);
			return data;
		},
	});

export const adminGetRoleQueryOptions = (
	id: string,
	config?: AxiosRequestConfig,
) =>
	queryOptions({
		queryKey: queryKeys.adminRoleDetail(id),
		queryFn: async () => {
			const { data } = await api.get<Role>(`/admin/roles/${id}`, config);
			return data;
		},
		enabled: !!id,
	});

export const adminListUsersQueryOptions = (config?: AxiosRequestConfig) =>
	queryOptions({
		queryKey: queryKeys.adminUsers,
		queryFn: async () => {
			const { data } = await api.get<PaginatedResponse<User>>(
				"/admin/users",
				config,
			);
			return data;
		},
	});

export const adminListTagsQueryOptions = (config?: AxiosRequestConfig) =>
	queryOptions({
		queryKey: queryKeys.adminTags,
		queryFn: async () => {
			const { data } = await api.get<Tag[]>("/admin/tags", config);
			return data;
		},
	});

export const adminListSeriesQueryOptions = (
	params?: AdminListSeriesParams,
	config?: AxiosRequestConfig,
) =>
	queryOptions({
		queryKey: queryKeys.adminSeries(params),
		queryFn: async () => {
			const { data } = await api.get<PaginatedResponse<Series>>(
				"/admin/series",
				{ ...config, params },
			);
			return data;
		},
	});

export const adminGetSeriesQueryOptions = (
	id: string,
	config?: AxiosRequestConfig,
) =>
	queryOptions({
		queryKey: queryKeys.adminSeriesDetail(id),
		queryFn: async () => {
			const { data } = await api.get<Series>(`/admin/series/${id}`, config);
			return data;
		},
		enabled: !!id,
	});

export const adminListChaptersQueryOptions = (
	id: string,
	config?: AxiosRequestConfig,
) =>
	queryOptions({
		queryKey: queryKeys.adminChapters(id),
		queryFn: async () => {
			const { data } = await api.get<Chapter[]>(
				`/admin/series/${id}/chapters`,
				config,
			);
			return data;
		},
		enabled: !!id,
	});

export const adminGetChapterQueryOptions = (
	id: string,
	config?: AxiosRequestConfig,
) =>
	queryOptions({
		queryKey: queryKeys.adminChapterDetail(id),
		queryFn: async () => {
			const { data } = await api.get<ChapterWithPages>(
				`/admin/chapters/${id}`,
				config,
			);
			return data;
		},
		enabled: !!id,
	});

export const adminGetSiteSettingsQueryOptions = (config?: AxiosRequestConfig) =>
	queryOptions({
		queryKey: queryKeys.adminSiteSettings,
		queryFn: async () => {
			const { data } = await api.get<SiteSettings>("/admin/settings", config);
			return data;
		},
	});

export const adminGetSystemInfoQueryOptions = (config?: AxiosRequestConfig) =>
	queryOptions({
		queryKey: queryKeys.adminSystemInfo,
		queryFn: async () => {
			const { data } = await api.get<SystemInfo>(
				"/admin/settings/system",
				config,
			);
			return data;
		},
	});

// ============================================================================
// Mutation Functions
// ============================================================================

export const signUp = async (
	request: SignUpRequest,
	config?: AxiosRequestConfig,
) => {
	const { data } = await api.post<AuthResponse>(
		"/auth/sign-up",
		request,
		config,
	);
	return data;
};

export const signIn = async (
	request: SignInRequest,
	config?: AxiosRequestConfig,
) => {
	const { data } = await api.post<AuthResponse>(
		"/auth/sign-in",
		request,
		config,
	);
	return data;
};

export const signOut = async (config?: AxiosRequestConfig) => {
	const { data } = await api.post<MessageResponse>(
		"/auth/sign-out",
		undefined,
		config,
	);
	return data;
};

export const verifyEmail = async (
	request: VerifyEmailRequest,
	config?: AxiosRequestConfig,
) => {
	const { data } = await api.post<MessageResponse>(
		"/auth/verify-email",
		request,
		config,
	);
	return data;
};

export const updateUser = async (
	request: UpdateUserRequest,
	config?: AxiosRequestConfig,
) => {
	const { data } = await api.patch<UpdateUserResponse>(
		"/auth/update-user",
		request,
		config,
	);
	return data;
};

export const changePassword = async (
	request: ChangePasswordRequest,
	config?: AxiosRequestConfig,
) => {
	const { data } = await api.post<MessageResponse>(
		"/auth/change-password",
		request,
		config,
	);
	return data;
};

export const requestEmailVerification = async (config?: AxiosRequestConfig) => {
	const { data } = await api.post<RequestVerificationResponse>(
		"/auth/request-verification",
		undefined,
		config,
	);
	return data;
};

export const revokeSession = async (
	request: RevokeSessionRequest,
	config?: AxiosRequestConfig,
) => {
	const { data } = await api.delete<MessageResponse>("/auth/sessions", {
		...config,
		data: request,
	});
	return data;
};

export const toggleBookmark = async (
	seriesId: string,
	config?: AxiosRequestConfig,
) => {
	const { data } = await api.post<ToggleBookmarkResponse>(
		`/bookmarks/${seriesId}`,
		undefined,
		config,
	);
	return data;
};

export const incrementSeriesView = async (
	id: string,
	config?: AxiosRequestConfig,
) => {
	const { data } = await api.post<MessageResponse>(
		`/series/${id}/view`,
		undefined,
		config,
	);
	return data;
};

export const incrementChapterView = async (
	id: string,
	config?: AxiosRequestConfig,
) => {
	const { data } = await api.post<MessageResponse>(
		`/chapters/${id}/view`,
		undefined,
		config,
	);
	return data;
};

export const adminUploadFile = async (config?: AxiosRequestConfig) => {
	const { data } = await api.post<AsyncUploadResponse>(
		"/admin/upload",
		undefined,
		config,
	);
	return data;
};

export const adminUploadMultipleFiles = async (config?: AxiosRequestConfig) => {
	const { data } = await api.post<AsyncBulkUploadResponse>(
		"/admin/upload/bulk",
		undefined,
		config,
	);
	return data;
};

export const adminCleanOrphanedFiles = async (config?: AxiosRequestConfig) => {
	const { data } = await api.delete<MessageResponse>(
		"/admin/upload/cleanup",
		config,
	);
	return data;
};

export const adminCreateRole = async (
	request: CreateRoleRequest,
	config?: AxiosRequestConfig,
) => {
	const { data } = await api.post<Role>("/admin/roles", request, config);
	return data;
};

export const adminUpdateRole = async (
	id: string,
	request: UpdateRoleRequest,
	config?: AxiosRequestConfig,
) => {
	const { data } = await api.patch<Role>(`/admin/roles/${id}`, request, config);
	return data;
};

export const adminDeleteRole = async (
	id: string,
	config?: AxiosRequestConfig,
) => {
	const { data } = await api.delete<MessageResponse>(
		`/admin/roles/${id}`,
		config,
	);
	return data;
};

export const adminAssignRole = async (
	request: AssignRoleRequest,
	config?: AxiosRequestConfig,
) => {
	const { data } = await api.post<MessageResponse>(
		"/admin/roles/assign",
		request,
		config,
	);
	return data;
};

export const adminRemoveRole = async (
	request: AssignRoleRequest,
	config?: AxiosRequestConfig,
) => {
	const { data } = await api.post<MessageResponse>(
		"/admin/roles/remove",
		request,
		config,
	);
	return data;
};

export const adminBanUser = async (
	request: BanUserRequest,
	config?: AxiosRequestConfig,
) => {
	const { data } = await api.post<MessageResponse>(
		"/admin/users/ban",
		request,
		config,
	);
	return data;
};

export const adminUnbanUser = async (
	id: string,
	config?: AxiosRequestConfig,
) => {
	const { data } = await api.post<MessageResponse>(
		`/admin/users/unban/${id}`,
		undefined,
		config,
	);
	return data;
};

export const adminCreateTag = async (
	request: CreateTagRequest,
	config?: AxiosRequestConfig,
) => {
	const { data } = await api.post<Tag>("/admin/tags", request, config);
	return data;
};

export const adminUpdateTag = async (
	id: string,
	request: UpdateTagRequest,
	config?: AxiosRequestConfig,
) => {
	const { data } = await api.patch<Tag>(`/admin/tags/${id}`, request, config);
	return data;
};

export const adminDeleteTag = async (
	id: string,
	config?: AxiosRequestConfig,
) => {
	const { data } = await api.delete<MessageResponse>(
		`/admin/tags/${id}`,
		config,
	);
	return data;
};

export const adminCreateSeries = async (
	request: CreateSeriesRequest,
	config?: AxiosRequestConfig,
) => {
	const { data } = await api.post<Series>("/admin/series", request, config);
	return data;
};

export const adminUpdateSeries = async (
	id: string,
	request: UpdateSeriesRequest,
	config?: AxiosRequestConfig,
) => {
	const { data } = await api.patch<Series>(
		`/admin/series/${id}`,
		request,
		config,
	);
	return data;
};

export const adminDeleteSeries = async (
	id: string,
	config?: AxiosRequestConfig,
) => {
	const { data } = await api.delete<MessageResponse>(
		`/admin/series/${id}`,
		config,
	);
	return data;
};

export const adminCreateChapter = async (
	id: string,
	request: CreateChapterRequest,
	config?: AxiosRequestConfig,
) => {
	const { data } = await api.post<Chapter>(
		`/admin/series/${id}/chapters`,
		request,
		config,
	);
	return data;
};

export const adminUpdateChapter = async (
	id: string,
	request: UpdateChapterRequest,
	config?: AxiosRequestConfig,
) => {
	const { data } = await api.patch<Chapter>(
		`/admin/chapters/${id}`,
		request,
		config,
	);
	return data;
};

export const adminDeleteChapter = async (
	id: string,
	config?: AxiosRequestConfig,
) => {
	const { data } = await api.delete<MessageResponse>(
		`/admin/chapters/${id}`,
		config,
	);
	return data;
};

export const adminAddPages = async (
	id: string,
	request: CreatePagesRequest,
	config?: AxiosRequestConfig,
) => {
	const { data } = await api.post<Page[]>(
		`/admin/chapters/${id}/pages`,
		request,
		config,
	);
	return data;
};

export const adminReorderPages = async (
	id: string,
	request: ReorderPagesRequest,
	config?: AxiosRequestConfig,
) => {
	const { data } = await api.post<MessageResponse>(
		`/admin/chapters/${id}/pages/reorder`,
		request,
		config,
	);
	return data;
};

export const adminUpdatePage = async (
	id: string,
	request: UpdatePageRequest,
	config?: AxiosRequestConfig,
) => {
	const { data } = await api.patch<Page>(`/admin/pages/${id}`, request, config);
	return data;
};

export const adminDeletePage = async (
	id: string,
	config?: AxiosRequestConfig,
) => {
	const { data } = await api.delete<MessageResponse>(
		`/admin/pages/${id}`,
		config,
	);
	return data;
};

export const adminUpdateSiteSettings = async (
	request: UpdateSiteSettingsRequest,
	config?: AxiosRequestConfig,
) => {
	const { data } = await api.put<SiteSettings>(
		"/admin/settings",
		request,
		config,
	);
	return data;
};

export const adminPerformMaintenanceAction = async (
	request: MaintenanceAction,
	config?: AxiosRequestConfig,
) => {
	const { data } = await api.post<MaintenanceActionResponse>(
		"/admin/settings/maintenance",
		request,
		config,
	);
	return data;
};

// ============================================================================
// Mutation Options
// ============================================================================

export const signUpMutationOptions = (config?: AxiosRequestConfig) =>
	mutationOptions({
		mutationFn: (request: SignUpRequest) => signUp(request, config),
	});

export const signInMutationOptions = (config?: AxiosRequestConfig) =>
	mutationOptions({
		mutationFn: (request: SignInRequest) => signIn(request, config),
	});

export const signOutMutationOptions = (config?: AxiosRequestConfig) =>
	mutationOptions({
		mutationFn: () => signOut(config),
	});

export const verifyEmailMutationOptions = (config?: AxiosRequestConfig) =>
	mutationOptions({
		mutationFn: (request: VerifyEmailRequest) => verifyEmail(request, config),
	});

export const updateUserMutationOptions = (config?: AxiosRequestConfig) =>
	mutationOptions({
		mutationFn: (request: UpdateUserRequest) => updateUser(request, config),
	});

export const changePasswordMutationOptions = (config?: AxiosRequestConfig) =>
	mutationOptions({
		mutationFn: (request: ChangePasswordRequest) =>
			changePassword(request, config),
	});

export const requestEmailVerificationMutationOptions = (
	config?: AxiosRequestConfig,
) =>
	mutationOptions({
		mutationFn: () => requestEmailVerification(config),
	});

export const revokeSessionMutationOptions = (config?: AxiosRequestConfig) =>
	mutationOptions({
		mutationFn: (request: RevokeSessionRequest) =>
			revokeSession(request, config),
	});

export const toggleBookmarkMutationOptions = (config?: AxiosRequestConfig) =>
	mutationOptions({
		mutationFn: (seriesId: string) => toggleBookmark(seriesId, config),
	});

export const incrementSeriesViewMutationOptions = (
	config?: AxiosRequestConfig,
) =>
	mutationOptions({
		mutationFn: (id: string) => incrementSeriesView(id, config),
	});

export const incrementChapterViewMutationOptions = (
	config?: AxiosRequestConfig,
) =>
	mutationOptions({
		mutationFn: (id: string) => incrementChapterView(id, config),
	});

export const adminUploadFileMutationOptions = (config?: AxiosRequestConfig) =>
	mutationOptions({
		mutationFn: () => adminUploadFile(config),
	});

export const adminUploadMultipleFilesMutationOptions = (
	config?: AxiosRequestConfig,
) =>
	mutationOptions({
		mutationFn: () => adminUploadMultipleFiles(config),
	});

export const adminCleanOrphanedFilesMutationOptions = (
	config?: AxiosRequestConfig,
) =>
	mutationOptions({
		mutationFn: () => adminCleanOrphanedFiles(config),
	});

export const adminCreateRoleMutationOptions = (config?: AxiosRequestConfig) =>
	mutationOptions({
		mutationFn: (request: CreateRoleRequest) =>
			adminCreateRole(request, config),
	});

export const adminUpdateRoleMutationOptions = (config?: AxiosRequestConfig) =>
	mutationOptions({
		mutationFn: ({ id, ...request }: { id: string } & UpdateRoleRequest) =>
			adminUpdateRole(id, request, config),
	});

export const adminDeleteRoleMutationOptions = (config?: AxiosRequestConfig) =>
	mutationOptions({
		mutationFn: (id: string) => adminDeleteRole(id, config),
	});

export const adminAssignRoleMutationOptions = (config?: AxiosRequestConfig) =>
	mutationOptions({
		mutationFn: (request: AssignRoleRequest) =>
			adminAssignRole(request, config),
	});

export const adminRemoveRoleMutationOptions = (config?: AxiosRequestConfig) =>
	mutationOptions({
		mutationFn: (request: AssignRoleRequest) =>
			adminRemoveRole(request, config),
	});

export const adminBanUserMutationOptions = (config?: AxiosRequestConfig) =>
	mutationOptions({
		mutationFn: (request: BanUserRequest) => adminBanUser(request, config),
	});

export const adminUnbanUserMutationOptions = (config?: AxiosRequestConfig) =>
	mutationOptions({
		mutationFn: (id: string) => adminUnbanUser(id, config),
	});

export const adminCreateTagMutationOptions = (config?: AxiosRequestConfig) =>
	mutationOptions({
		mutationFn: (request: CreateTagRequest) => adminCreateTag(request, config),
	});

export const adminUpdateTagMutationOptions = (config?: AxiosRequestConfig) =>
	mutationOptions({
		mutationFn: ({ id, ...request }: { id: string } & UpdateTagRequest) =>
			adminUpdateTag(id, request, config),
	});

export const adminDeleteTagMutationOptions = (config?: AxiosRequestConfig) =>
	mutationOptions({
		mutationFn: (id: string) => adminDeleteTag(id, config),
	});

export const adminCreateSeriesMutationOptions = (config?: AxiosRequestConfig) =>
	mutationOptions({
		mutationFn: (request: CreateSeriesRequest) =>
			adminCreateSeries(request, config),
	});

export const adminUpdateSeriesMutationOptions = (config?: AxiosRequestConfig) =>
	mutationOptions({
		mutationFn: ({ id, ...request }: { id: string } & UpdateSeriesRequest) =>
			adminUpdateSeries(id, request, config),
	});

export const adminDeleteSeriesMutationOptions = (config?: AxiosRequestConfig) =>
	mutationOptions({
		mutationFn: (id: string) => adminDeleteSeries(id, config),
	});

export const adminCreateChapterMutationOptions = (
	config?: AxiosRequestConfig,
) =>
	mutationOptions({
		mutationFn: ({ id, ...request }: { id: string } & CreateChapterRequest) =>
			adminCreateChapter(id, request, config),
	});

export const adminUpdateChapterMutationOptions = (
	config?: AxiosRequestConfig,
) =>
	mutationOptions({
		mutationFn: ({ id, ...request }: { id: string } & UpdateChapterRequest) =>
			adminUpdateChapter(id, request, config),
	});

export const adminDeleteChapterMutationOptions = (
	config?: AxiosRequestConfig,
) =>
	mutationOptions({
		mutationFn: (id: string) => adminDeleteChapter(id, config),
	});

export const adminAddPagesMutationOptions = (config?: AxiosRequestConfig) =>
	mutationOptions({
		mutationFn: ({ id, ...request }: { id: string } & CreatePagesRequest) =>
			adminAddPages(id, request, config),
	});

export const adminReorderPagesMutationOptions = (config?: AxiosRequestConfig) =>
	mutationOptions({
		mutationFn: ({ id, ...request }: { id: string } & ReorderPagesRequest) =>
			adminReorderPages(id, request, config),
	});

export const adminUpdatePageMutationOptions = (config?: AxiosRequestConfig) =>
	mutationOptions({
		mutationFn: ({ id, ...request }: { id: string } & UpdatePageRequest) =>
			adminUpdatePage(id, request, config),
	});

export const adminDeletePageMutationOptions = (config?: AxiosRequestConfig) =>
	mutationOptions({
		mutationFn: (id: string) => adminDeletePage(id, config),
	});

export const adminUpdateSiteSettingsMutationOptions = (
	config?: AxiosRequestConfig,
) =>
	mutationOptions({
		mutationFn: (request: UpdateSiteSettingsRequest) =>
			adminUpdateSiteSettings(request, config),
	});

export const adminPerformMaintenanceActionMutationOptions = (
	config?: AxiosRequestConfig,
) =>
	mutationOptions({
		mutationFn: (request: MaintenanceAction) =>
			adminPerformMaintenanceAction(request, config),
	});
